CREATE TABLE IF NOT EXISTS mensaje (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contenido VARCHAR(255),
    fecha_envio TIMESTAMP,
    emisor_id UUID REFERENCES usuario(id),
    receptor_id UUID REFERENCES usuario(id)
);

CREATE TABLE IF NOT EXISTS mensaje_curso_leido (
    id UUID PRIMARY KEY,
    curso_id UUID,
    usuario_id UUID,
    ultimo_mensaje_leido_id UUID
);

CREATE TABLE IF NOT EXISTS notificaciones (
    id UUID PRIMARY KEY,
    mensaje VARCHAR(255),
    leida BOOLEAN NOT NULL,
    fecha TIMESTAMP,
    tipo VARCHAR(255),
    usuario_id UUID NOT NULL REFERENCES usuario(id)
);
